### PR TITLE
SD-1838: Add conditions to service and timestamp properties

### PR DESCRIPTION
**Pull request by HenrikHL**
### **User description**
[SD-1838](https://dcsa.atlassian.net/browse/SD-1838): Update conditions on many PortCallService and Timestamp properties
@jkosternl an FYI to be included in the Conformance Toolkit

[SD-1838]: https://dcsa.atlassian.net/browse/SD-1838?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

___

### **PR Type**
enhancement

___

### **Description**
- Added specific conditions for `eventTypeCode` usage based on `portCallServiceType`, ensuring that certain event types are only applicable to specific services.
- Introduced conditions for `serviceDirection` to restrict its usage with certain `portCallServiceType` values.
- Defined conditions for `facilityCode` to ensure it is used appropriately with corresponding `portCallServiceType`.
- Specified conditions for `timestampTypeCode` in `Timestamp`, detailing when each type can be used by providers and consumers.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>JIT_v2.0.0.yaml</strong><dd><code>Add conditional logic to service and timestamp properties</code></dd></summary>
<hr>

jit/v2/JIT_v2.0.0.yaml

<li>Added conditions for <code>eventTypeCode</code> based on <code>portCallServiceType</code>.<br> <li> Introduced conditions for <code>serviceDirection</code> with specific <br><code>portCallServiceType</code>.<br> <li> Defined conditions for <code>facilityCode</code> usage with <code>portCallServiceType</code>.<br> <li> Specified conditions for <code>timestampTypeCode</code> usage in <code>Timestamp</code>.<br>

</details>

  </td>
  <td><a href="https://github.com/dcsaorg/DCSA-OpenAPI/pull/455/files#diff-9515d70681d4860776aad1fa65c622e5b362021ad1f0c0ae1352067f49108299">+104/-0</a>&nbsp; </td>

</tr>
</table></td></tr></tr></tbody></table>

___

> 🔍 To retrieve JIRA tickets as context to your PR description, please [register](https://qodo-merge-docs.qodo.ai/core-abilities/fetching_ticket_context/#jira-cloud) your organization.

### CODE REVIEW

**Comment by HenrikHL** [comment]
@emiliodcsa  this one is for you:
image

**Review by jkosternl — APPROVED** [review]
Fine by me, but should be verified by others (like PO). So, wait with merging please.

**Comment by emiliodcsa** [comment]
> @emiliodcsa this one is for you: image

Hi. 

**For the ones with CAN** - probably a better word is preferred? 

- **Condition:** `STRT` and `CMPL` - can only be used with the following `portCallServiceType`:

              - `CARGO_OPERATIONS` (Cargo operations)
              - etc etc etc
means: if STRT or CMPL are used with anything that is not in the list, is wrong, is not a logical combination. needs to be validated in conformance. 

-   **Condition:** both `ARRI` and `DEPA` can only be used with `portCallServiceType='BERTH'` (Berth)

means: if berth is used with anything else than ARRI or DEPA, is wrong, is not a logical combination. needs to be validated in conformance. 

-  **Condition:** `ARRI` can only be used with the following `portCallServiceType`:

              - `PILOT_BOARDING_PLACE` (Pilot Boarding Place)
              - `ALL_FAST` (All Fast)
              - `GANGWAY_DOWN_AND_SECURE` (Gangway down and secure)
              - `VESSEL_READY_FOR_CARGO_OPERATIONS` (Vessel Ready for cargo operations)
              - `VESSEL_READY_TO_SAIL` (Vessel Ready to sail)
              - `MOVES` (Moves)
 means: if any of the services in the list is used with anything that is not ARRI, is wrong, could sound logical but is not meant to be used. needs to be validated in conformance. 

- **Condition:** `DEPA` can only be used with the following `portCallServiceType`:

              - `SAFETY` (Safety)
  means: if any of the services in the  list uses something that is not DEPA, is wrong, could sound logical but is not meant to be used. needs to be validated i conformance. 

**For the ones with SHOULD**, 

means the enum should be used with the services in the list, but because it could be empty and because of different practices it could be that they are used differently. we wont enforce a validation in conformance, but we suggest in the API what are expected combinations. 

- **Condition:** `INBD` should only be used with the following `portCallServiceType`:

              - `BERTH` (Berth)

@HenrikHL @jkosternl

**Comment by HenrikHL** [comment]
> > @emiliodcsa this one is for you: image
> 
> Hi.
> 
> **For the ones with CAN** - probably a better word is preferred?
> 
> * **Condition:** `STRT` and `CMPL` - can only be used with the following `portCallServiceType`:
>   ```
>           - `CARGO_OPERATIONS` (Cargo operations)
>           - etc etc etc
>   ```
> 
> means: if STRT or CMPL are used with anything that is not in the list, is wrong, is not a logical combination. needs to be validated in conformance.
> 
> * **Condition:** both `ARRI` and `DEPA` can only be used with `portCallServiceType='BERTH'` (Berth)
> 
> means: if berth is used with anything else than ARRI or DEPA, is wrong, is not a logical combination. needs to be validated in conformance.
> 
> * **Condition:** `ARRI` can only be used with the following `portCallServiceType`:
>   ```
>          - `PILOT_BOARDING_PLACE` (Pilot Boarding Place)
>          - `ALL_FAST` (All Fast)
>          - `GANGWAY_DOWN_AND_SECURE` (Gangway down and secure)
>          - `VESSEL_READY_FOR_CARGO_OPERATIONS` (Vessel Ready for cargo operations)
>          - `VESSEL_READY_TO_SAIL` (Vessel Ready to sail)
>          - `MOVES` (Moves)
>   ```
> 
> means: if any of the services in the list is used with anything that is not ARRI, is wrong, could sound logical but is not meant to be used. needs to be validated in conformance.
> 
> * **Condition:** `DEPA` can only be used with the following `portCallServiceType`:
>   ```
>           - `SAFETY` (Safety)
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   means: if any of the services in the  list uses something that is not DEPA, is wrong, could sound logical but is not meant to be used. needs to be validated i conformance.
> 
> **For the ones with SHOULD**,
> 
> means the enum should be used with the services in the list, but because it could be empty and because of different practices it could be that they are used differently. we wont enforce a validation in conformance, but we suggest in the API what are expected combinations.
> 
> * **Condition:** `INBD` should only be used with the following `portCallServiceType`:
>   ```
>           - `BERTH` (Berth)
>   ```
> 
> @HenrikHL @jkosternl

I don't see any problem with the above - I think it is quite clear (and also how I understand it)...

**Comment by HenrikHL** [comment]
I will not change anything unless someone else thinks they can come up with a better suggestion ;-)

**Comment by HenrikHL** [comment]
I will not merge this until you @palatsangeetha have approved...

**Comment by jkosternl** [comment]
> means: if STRT or CMPL are used with anything that is not in the list, is wrong, is not a logical combination. needs to be validated in conformance.

Hi @emiliodcsa, on all the things which need to be validated with Conformance scenarios, do you put them somewhere (Confluence / Jira issue), so I don't have to capture these from some PRs?

**Comment by emiliodcsa** [comment]
> > means: if STRT or CMPL are used with anything that is not in the list, is wrong, is not a logical combination. needs to be validated in conformance.
> 
> Hi @emiliodcsa, on all the things which need to be validated with Conformance scenarios, do you put them somewhere (Confluence / Jira issue), so I don't have to capture these from some PRs?

I have it in the data overview. Let me add it in the confluence page with the conformance scenarios.

**Review by palatsangeetha — APPROVED** [review]
The changes looks good to me

**Comment by emiliodcsa** [comment]
Hi @HenrikHL I know this was merged already. I have added the conditions in Confluence and rephrased a bit using what you wrote. We can reopen the story and update the spec if you think they are better described. 

https://dcsa.atlassian.net/wiki/spaces/APV/pages/518553602/20240930_DCSA_JIT_2.0_ConformanceScenarios#Conditions

**Pull request merged**
