### PR TITLE
DT-1802,DT-1804: Create and populate License objects

### PR DESCRIPTION
**Pull request by HenrikHL**
[DT-1802](https://dcsa.atlassian.net/browse/DT-1802),[DT-1804](https://dcsa.atlassian.net/browse/DT-1804): Update Export and Import license / declaration in BKG
- make `isExportDeclarationRequired` optional and change description
- change description of `exportDeclarationReference`
- create `ExportLicense` and `ImportLicense` object on `Commodity`
  - add 4 optional properties (explained in the issue)
- remove `isImportLicenseRequired` and `importLicenseReference` from Booking root level
- remove `isExportLicenseRequired` and `exportLicenseReference` from Commodity level

[DT-1802]: https://dcsa.atlassian.net/browse/DT-1802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DT-1804]: https://dcsa.atlassian.net/browse/DT-1804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by palatsangeetha — APPROVED** [review]
The changes looks good

**Comment by douradofrazer** [comment]
@CodiumAI-Agent /describe
--pr_description.publish_description_as_comment=true

**Comment by douradofrazer** [comment]
@CodiumAI-Agent /review
--pr_reviewer.inline_code_comments=true
--pr_reviewer.require_score_review=true

**Comment by douradofrazer** [comment]
@CodiumAI-Agent /describe
--pr_description.extra_instructions= Give me a detailed breakdown of the changes."
For the title, use the format [type]: [summary]
"
--pr_description.publish_description_as_comment=true

**Comment by douradofrazer** [comment]
@CodiumAI-Agent /describe
--pr_description.extra_instructions="
For the title, use the format [type]: [summary]
And cover each line change, group if required.
"
--pr_description.publish_description_as_comment=true

**Comment by douradofrazer** [comment]
@CodiumAI-Agent /describe
--pr_description.extra_instructions="
For the title, use the format [type]: [summary]
And cover each line change, group if required.
"
--pr_description.publish_description_as_comment=true

**Pull request merged**
